name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CheckCtest:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: |
        mkdir build
        cd build
        cmake ..
        cmake --build 
        ctests
  checkcpp:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        pip install cpplint
        cpplint tests.cpp
        which cpplint
